events {}

http {
    resolver 127.0.0.11 valid=30s; # нужно для понимания nginx'ом, что приложуха соответствует ip'шнику контейнера

    geo $is_block
    {
        default 0;
        213.0.0.0/32 1;
        95.161.0.0/32 1;
        84.237.54.110/24 1;
        84.237.54.65/24 1;
        84.237.54.98/24 1;
        172.17.0.1/16 1;
    }

    server
    {
        listen 80;
        listen [::]:80;
        charset utf-8;

        # Читаем реальный IP
        set_real_ip_from 0.0.0.0/0; 
        real_ip_header X-Forwarded-For;
        real_ip_recursive on; # Искать ip рекурсивно, если прокси было несколько

        location = /access-denied
        {
            default_type text/html;
            return 200 "<html><head><meta charset='utf-8'><title>Блокировка</title></head><body><center><h1 style='color:red; margin-top:100px;'>ВСЕ-ГО ХО-РО-ШЕ-ГО</h1><p>Доступ из вашего региона закрыт, хехехехехе :)</p></center></body></html>";
        }

        location /
        {
            if ($is_block)
            {
                return 302 /access-denied;
            }

            set $upstream app_cont;
            proxy_pass http://$upstream:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}

